<Project>
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <VersionPrefix Condition="'$(VersionPrefix)' == ''">0.1.0</VersionPrefix>
        <Authors>Raffaele Rialdi (@raffaeler)</Authors>
        <PackageTags>Console;Terminal;Interactive;Menu</PackageTags>
        <PackageIcon>Logo.png</PackageIcon>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <Description>A library used to write Interactive terminal apps.</Description>
        <PackageProjectUrl>https://github.com/raffaeler/PowerCLI</PackageProjectUrl>
        <RepositoryUrl>https://github.com/raffaeler/PowerCLI</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <GenerateRepositoryUrlAttribute>true</GenerateRepositoryUrlAttribute>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <DebugType>portable</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <Deterministic>true</Deterministic>
        <EnableSourceControlManagerQueries>true</EnableSourceControlManagerQueries>
        <EnableSourceLink>true</EnableSourceLink>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <ContinuousIntegrationBuild Condition="'$(ContinuousIntegrationBuild)' == '' and ('$(CI)' == 'true' or '$(GITHUB_ACTIONS)' == 'true' or '$(TF_BUILD)' == 'true')">true</ContinuousIntegrationBuild>
    </PropertyGroup>
    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)..\Logo.png" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)..\README.md" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)..\LICENSE" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>
